---
- name: config | configuring kea dhcp services (RedHat)
  template:
    src: "etc/kea/kea.conf.j2"
    dest: "/etc/kea/kea.conf"
    owner: "root"
    group: "root"
    mode: "o=rw,g=r,o=r"
  notify:
    - 'restart redhat kea-dhcp'
  when: ansible_os_family == "RedHat"

- name: config | configuring kea dhcp services (Debian)
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "o=rw,g=r,o=r"
  notify:
    - 'restart {{ ansible_os_family|lower }} kea-dhcp'
  with_items:
    - 'etc/kea/kea-dhcp-ddns.conf'
    - 'etc/kea/kea-dhcp4.conf'
  when: ansible_os_family == "Debian"
