---
- name: apparmor | disabling apparmor profiles for libvirt
  file:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    state: "link"
  register: "libvirt_apparmor_disabled"
  become: true
  with_items:
    - src: '/etc/apparmor.d/usr.sbin.libvirtd'
      dest: '/etc/apparmor.d/disable/usr.sbin.libvirtd'
    - src: '/etc/apparmor.d/usr.lib.libvirt.virt-aa-helper'
      dest: '/etc/apparmor.d/disable/usr.lib.libvirt.virt-aa-helper'

- name: apparmor | disabling apparmor profiles for libvirt
  command: "apparmor_parser -R {{ item }}"
  become: true
  with_items:
    - '/etc/apparmor.d/usr.sbin.libvirtd'
    - '/etc/apparmor.d/usr.lib.libvirt.virt-aa-helper'
  when: libvirt_apparmor_disabled['changed']
