---
- name: config | Configuring Redis
  template:
    src: "etc/redis/redis.conf.j2"
    dest: "{{ redis_conf }}"
  notify: "restart {{ redis_service }}"

- name: config | Configuring Sysctl Settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "present"
    reload: yes
  notify: "restart {{ redis_service }}"
  with_items: '{{ redis_sysctl_settings }}'
