---
- name: debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'python-pip'
    - 'ruby'
    - 'rubygems-integration'

- name: debian | Installing Redis
  apt:
    name: "redis-server"
    state: "present"
  when: not redis_install_from_source
