---
- name: configure_root_access | updating root passwords
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_mysql_root_password }}"
  become: true
  run_once: true
  with_items:
    - '{{ ansible_hostname }}'
    - '127.0.0.1'
    - '::1'
    - localhost

- name: configure_root_access | configuring root my.cnf
  template:
    src: "root/my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=,o="
  become: true
  when: ansible_os_family == "RedHat"

- name: configure_root_access | updating root passwords
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_mysql_root_password }}"
  become: true
  with_items:
    - '{{ ansible_hostname }}'
    - '127.0.0.1'
    - '::1'
    - localhost

- name: configure_root_access | updating root passwords (allow from anywhere)
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mariadb_mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  become: true
  with_items:
    - '%'
  when: galera_allow_root_from_any
