---
- name: redhat | installing packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
  when: >
        ansible_distribution == "Fedora"

- name: redhat | configuring ntp
  template:
    src: "etc/ntp.conf.j2"
    dest: "/etc/ntp.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart ntpd

- name: redhat | ensuring ntpd service is started and enabled on boot
  service:
    name: "ntpd"
    state: started
    enabled: yes
