---
- name: domain_users | generate list of users
  command: "samba-tool user list"
  register: domain_users

- name: domain_users | creating domain users
  command: "samba-tool user add {{ item['name'] }} '{{ item['password'] }}'"
#  ignore_errors: true   #defined for now to get around potential bug in failed_when conditionals
  with_items: '{{ samba_domain_users }}'
  when: item['name'] not in domain_users['stdout']
