---
# handlers file for ansible-haproxy
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
  when: not ansible_check_mode

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  when: not ansible_check_mode
