---
# tasks file for ansible-docker
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_docker.yml
  when: docker_config_service

- include: users.yml
  when: >
        docker_config_users is defined and
        docker_config_users

- include: manage_python_modules.yml

- include: images.yml
  when: >
        docker_manage_images and
        docker_images is defined
