---
# tasks file for ansible-sensu
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: config_server.yml
  when: sensu_server

- include: config_plugins.yml

- include: config_checks.yml

- include: config_client.yml
  when: sensu_client

- include: config_handlers.yml
  when: >
        sensu_server and
        sensu_enable_handlers

- include: upgrade_sensu.yml
  when: >
        upgrade_sensu is defined and
        upgrade_sensu

- include: restart_sensu.yml
  when: >
        restart_sensu is defined and
        restart_sensu
