---
- name: debian | installing pre-requisites
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'python-pip'

- name: debian | installing redis-server
  apt:
    name: "redis-server"
    state: "present"

- name: debian | installing redis python module
  pip:
    name: "redis"
    state: "present"

- name: debian | configuring redis-server to listen on all interfaces
  replace:
    dest: "/etc/redis/redis.conf"
    regexp: "^bind 127.0.0.1"
    replace: "#bind 127.0.0.1"
  notify: 'restart redis-server'
  when: >
        redis_allow_remote_connections is defined and
        redis_allow_remote_connections
