---
- name: opensuse | installing dependencies
  zypper:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'python-devel'
    - 'python-pip'

- name: opensuse | installing redis
  zypper:
    name: "redis"
    state: "present"
  notify:
    - 'start redis'

- name: opensuse | configuring redis-server to listen on all interfaces
  replace:
    dest: "/etc/redis.conf"
    regexp: "^bind 127.0.0.1"
    replace: "#bind 127.0.0.1"
  notify: 'restart redis'
  when: >
        redis_allow_remote_connections is defined and
        redis_allow_remote_connections
