---
- name: config_cluster | waiting for api port
  wait_for:
    port: 8091

- name: config_cluster | checking if cluster is already created
  stat:
    path: "/var/log/.couchbase_cluster_created"
  register: couchbase_cluster_created
  with_items: groups['couchbase-master']
  when: >
        inventory_hostname == item
    
- name: config_cluster | creating cluster
  shell: "{{ couchbase_cli }} cluster-init -c 127.0.0.1:8091 --cluster-init-username={{ couchbase_admin_user }} --cluster-init-password={{ couchbase_admin_pass }} --cluster-init-port=8091 --cluster-init-ramsize={{ couchbase_cluster_ram_quota }} --service='data;index;query'"
  register: cluster_created
  with_items: groups['couchbase-master']
  when: >
        (inventory_hostname == item) and
        not couchbase_cluster_created.results[0].stat.exists

- name: config_cluster | marking cluster as created
  file:
    dest: "/var/log/.couchbase_cluster_created"
    state: touch
  with_items: groups['couchbase-master']
  when: >
        (inventory_hostname == item) and
        cluster_created.results[0].changed

- name: config_cluster | checking if joined to cluster
  stat:
    path: "/var/log/.couchbase_joined_cluster"
  register: couchbase_joined_cluster
  with_items: groups['couchbase-master']
  when: >
        inventory_hostname != item  

- name: config_cluster | joining cluster
  shell: "{{ couchbase_cli }} rebalance -c {{ hostvars[item].ansible_ssh_host }}:8091 -u {{ couchbase_admin_user }} -p {{ couchbase_admin_pass }} --server-add={{ ansible_ssh_host }}:8091 --server-add-username={{ couchbase_admin_user }} --server-add-password={{ couchbase_admin_pass }} --service='data;index;query'"
  register: joined_cluster
  with_items: groups['couchbase-master']
  when: >
        (inventory_hostname != item) and
        not couchbase_joined_cluster.results[0].stat.exists

- name: config_cluster | marking as joined cluster
  file:
    dest: "/var/log/.couchbase_joined_cluster"
    state: touch
  with_items: groups['couchbase-master']
  when: >
        (inventory_hostname != item) and
        joined_cluster.results[0].changed
