---
- name: redhat | installing haproxy and socat
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'haproxy'
    - 'hatop'
    - 'socat'
  when: ansible_distribution != "Fedora"

- name: redhat | installing haproxy and socat
  dnf:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'haproxy'
    - 'hatop'
    - 'socat'
  when: ansible_distribution == "Fedora"

- name: redhat | ensuring haproxy is enabled
  service:
    name: "haproxy"
    enabled: yes
  when: not ansible_check_mode
