---
# handlers file for ansible-ntp
- name: restart ntp
  service:
    name: "ntp"
    state: "restarted"
  when: not ansible_check_mode

- name: restart ntpd
  service:
    name: "ntpd"
    state: "restarted"
  when: not ansible_check_mode
