---
- name: configure_firewall | configuring UFW logging
  ufw:
    logging: "{{ ufw_logging }}"
  when: ufw_logging is defined

- name: configure_firewall | configuring UFW state
  ufw:
    state: "{{ ufw_state }}"
  when: ufw_state is defined

- name: configure_firewall | configuring UFW rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    proto: "{{ item.proto }}"
    rule: "{{ item.rule }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port }}"
  with_items: ufw_rules
  when: ufw_rules is defined

- name: configure_firewall | setting default UFW policies (incoming, outgoing)
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items: ufw_policies
  when: item.direction != "routed"

- name: configure_firewall | setting default UFW policies (routed)
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items: ufw_policies
  when: item.direction == "routed" and ansible_distribution != "Debian"
