export OS_PROJECT_DOMAIN_ID=default
export OS_USER_DOMAIN_ID=default
export OS_PROJECT_NAME=admin
export OS_TENANT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=29b1416692cb38014ea0
export OS_AUTH_URL=openstack.vagrant.local:35357
export OS_VOLUME_API_VERSION=2
