---
- name: config | Ensuring Guacamole Folders Exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
  become: true
  with_items:
    - /etc/guacamole
    - /etc/guacamole/lib
    - /etc/guacamole/extensions

- name: config | Configuring guacamole.properties
  template:
    src: etc/guacamole/guacamole.properties.j2
    dest: /etc/guacamole/guacamole.properties
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat }}"
    - restart guacd

- name: config | Configuring user-mapping.xml
  template:
    src: etc/guacamole/user-mapping.xml.j2
    dest: /etc/guacamole/user-mapping.xml
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat }}"
    - restart guacd
  when: not guacamole_mysql_auth

- name: config | Downloading Auth JDBC Library
  unarchive:
    src: "{{ guacamole_dl_url + '/binary/' + guacamole_auth_jdbc_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Copying Auth JDBC Connector
  copy:
    src: "{{ guacamole_src_dir + '/' + 'guacamole-auth-jdbc-' + guacamole_version + '/mysql/' + 'guacamole-auth-jdbc-mysql-' + guacamole_version + '.jar' }}"
    dest: /etc/guacamole/extensions/
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Downloading MySQL Connector
  unarchive:
    src: "{{ guacamole_mysql_connector_package }}"
    dest: "{{ guacamole_src_dir }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Copying MySQL Connector
  copy:
    src: "{{ guacamole_src_dir + '/' + 'mysql-connector-java-' + guacamole_mysql_connector_version + '/' +'mysql-connector-java-' + guacamole_mysql_connector_version + '.jar' }}"
    dest: /etc/guacamole/lib/
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
    remote_src: true
  become: true
  when: guacamole_mysql_auth

- name: config | Creating Guacamole DB
  mysql_db:
    name: "{{ guacamole_mysql_db['name'] }}"
    login_host: "{{ guacamole_mysql_db['host'] }}"
    login_port: "{{ guacamole_mysql_db['port'] }}"
    state: present
  become: true
  when: guacamole_mysql_auth

- name: config | Creating Guacamole DB User
  mysql_user:
    name: "{{ guacamole_mysql_db['username'] }}"
    password: "{{ guacamole_mysql_db['password'] }}"
    login_host: "{{ guacamole_mysql_db['host'] }}"
    login_port: "{{ guacamole_mysql_db['port'] }}"
    priv: "{{ guacamole_mysql_db['name'] + '.*:GRANT,SELECT,INSERT,UPDATE,DELETE' }}"
    state: present
  become: true
  when: guacamole_mysql_auth

- name: config | Checking If DB Has Been Populated
  stat:
    path: /etc/guacamole/.db_populated
  register: _guacamole_db_populated_check
  when: guacamole_mysql_auth

- name: config | Popluating DB
  mysql_db:
    name: "{{ guacamole_mysql_db['name'] }}"
    login_host: "{{ guacamole_mysql_db['host'] }}"
    login_port: "{{ guacamole_mysql_db['port'] }}"
    state: import
    target: "{{ guacamole_src_dir + '/' + 'guacamole-auth-jdbc-' + guacamole_version + '/mysql/schema/' + item }}"
  become: true
  register: _guacamole_db_populated
  notify:
    - "restart {{ guacamole_tomcat }}"
    - restart guacd
  with_items:
    - 001-create-schema.sql
    - 002-create-admin-user.sql
  when: >
    guacamole_mysql_auth and
    not _guacamole_db_populated_check['stat']['exists']

- name: config | Marking DB As Populated
  file:
    path: /etc/guacamole/.db_populated
    state: touch
  become: true
  when: >
    guacamole_mysql_auth and
    _guacamole_db_populated['changed']

- name: config | Creating Tomcat symlink For guacamole.properties
  file:
    src: /etc/guacamole
    dest: "{{ '/usr/share/' + guacamole_tomcat + '/.guacamole' }}"
    state: link
    owner: "{{ guacamole_tomcat }}"
    group: "{{ guacamole_tomcat }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat }}"
    - restart guacd
