---
# tasks file for ansible-nginx
- include: set_facts.yml

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_php.yml
  when: nginx_enable_php

- include: config_nginx.yml
  when: config_nginx
