---
# tasks file for ansible-base
- include: debian.yml
  tags:
    - base
  when: ansible_os_family == "Debian"

- include: debian_update_dns_nameservers.yml
  tags:
    - update_dns_nameservers
  when: >
        ansible_os_family == "Debian" and
        base_update_dns_nameservers

- include: debian_update_dns_search.yml
  tags:
    - update_dns_search
  when: >
        ansible_os_family == "Debian" and
        base_update_dns_search

- include: redhat.yml
  tags:
    - base
  when: ansible_os_family == "RedHat"

# - include: generate_rundeck_resources.yml
#   tags:
#     - generate_rundeck_resources
#   when: >
#         base_rundeck_generate_resources_xml and
#         base_rundeck_server is defined
