---
- name: alpine | Ensuring Edge Repo Is Enabled
  lineinfile:
    path: "/etc/apk/repositories"
    regexp: "^http://dl-cdn.alpinelinux.org/alpine/edge/community"
    line: "http://dl-cdn.alpinelinux.org/alpine/edge/community"
    state: "present"
  register: "_apk_repos_updated"
  become: true

- name: alpine | Updating APK Cache
  apk:
    update_cache: true
  become: true
  when: _apk_repos_updated['changed']

- name: alpine | Installing Docker
  apk:
    name: "docker"
    state: "present"
  become: true
