---
# handlers file for ansible-consul
- name: restart consul
  service:
    name: "consul"
    state: restarted
    sleep: 10

- name: start consul
  service:
    name: "consul"
    state: started

- name: stop consul
  service:
    name: "consul"
    state: stopped

- name: restart dnsmasq
  service:
    name: "dnsmasq"
    state: restarted

- name: restart haproxy
  service:
    name: "haproxy"
    state: restarted

- name: restart keepalived
  service:
    name: "keepalived"
    state: restarted
