---
- name: fedora | installing pre-reqs
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - wget

- name: fedora | installing erlang
  dnf:
    name: "erlang"
    state: present

- name: fedora | adding RabbitMQ public GPG key
  rpm_key:
    key: "{{ rabbitmq_redhat_repo_key }}"
    state: present

- name: fedora | downloading RabbitMQ
  get_url:
    url: "{{ rabbitmq_redhat_url }}/{{ rabbitmq_redhat_package }}"
    dest: "/opt/{{ rabbitmq_redhat_package }}"

- name: fedora | installing RabbitMQ
  dnf:
    name: "/opt/{{ rabbitmq_redhat_package }}"
    state: present

- name: fedora | starting and enabling RabbitMQ service
  service:
    name: "rabbitmq-server"
    state: started
    enabled: yes

- name: fedora | enabling the RabbitMQ Management Console
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify: restart rabbitmq-server
