# tasks file for ansible-rabbitmq
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- include: fedora.yml
  when: ansible_distribution == "Fedora"

- name: checking to see if already clustered
  stat: path=/etc/rabbitmq/clustered
  register: clustered

- include: rabbitmq_clustering.yml
  when: rabbitmq_enable_clustering and (clustered.stat.exists != True)

- include: rabbitmq_ha_config.yml
  when: rabbitmq_config_ha and rabbitmq_enable_clustering

- include: rabbitmq_users.yml
