---
- name: install | Checking For Previous Install Of HashiCorp Vault
  stat:
    path: "{{ hashi_vault_install_dir }}/vault"
  register: "_hashi_vault_install"
  check_mode: no
  tags:
    - 'hashi_vault_show_version'

- name: install | Capturing HashiCorp Vault Installed Version (If Installed)
  shell: "{{ hashi_vault_install_dir }}/vault version | awk '{ print substr($2,2) }'"
  register: "_hashi_vault_version"
  changed_when: false
  check_mode: no
  tags:
    - 'hashi_vault_show_version'
  when: _hashi_vault_install['stat']['exists']

- name: install | Showing HashiCorp Vault Installed Version (If Installed)
  debug: msg="HashiCorp Vault Version Installed{{ ':' }} {{ _hashi_vault_version['stdout'] }}"
  tags:
    - 'hashi_vault_show_version'
  when: >
        _hashi_vault_install['stat']['exists']

- name: install | Downloading HashiCorp Vault (i386)
  get_url:
    url: "{{ hashi_vault_url }}/vault/{{ hashi_vault_version }}/vault_{{ hashi_vault_version }}_linux_386.zip"
    dest: "/opt/vault_{{ hashi_vault_version }}_linux_386.zip"
    validate_certs: no
  become: true
  when: >
        ansible_machine == "i386" and
        (not _hashi_vault_install['stat']['exists'] or
        (_hashi_vault_install['stat']['exists'] and
        _hashi_vault_version['stdout'] != hashi_vault_version))

- name: install | Downloading HashiCorp Vault (x86_64)
  get_url:
    url: "{{ hashi_vault_url }}/vault/{{ hashi_vault_version }}/vault_{{ hashi_vault_version }}_linux_amd64.zip"
    dest: "/opt/vault_{{ hashi_vault_version }}_linux_amd64.zip"
    validate_certs: no
  become: true
  when: >
        ansible_machine == "x86_64" and
        (not _hashi_vault_install['stat']['exists'] or
        (_hashi_vault_install['stat']['exists'] and
        _hashi_vault_version['stdout'] != hashi_vault_version))

- name: install | Installing HashiCorp Vault (i386)
  unarchive:
    src: "/opt/vault_{{ hashi_vault_version }}_linux_386.zip"
    dest: "{{ hashi_vault_install_dir }}/"
    copy: no
  become: true
  when: >
        ansible_machine == "i386" and
        not ansible_check_mode and
        (not _hashi_vault_install['stat']['exists'] or
        (_hashi_vault_install['stat']['exists'] and
        _hashi_vault_version['stdout'] != hashi_vault_version))

- name: install | Installing HashiCorp Vault (x86_64)
  unarchive:
    src: "/opt/vault_{{ hashi_vault_version }}_linux_amd64.zip"
    dest: "{{ hashi_vault_install_dir }}/"
    copy: no
  become: true
  when: >
        ansible_machine == "x86_64" and
        not ansible_check_mode and
        (not _hashi_vault_install['stat']['exists'] or
        (_hashi_vault_install['stat']['exists'] and
        _hashi_vault_version['stdout'] != hashi_vault_version))
